name: CI
on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.8'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v1
      - run: |
          julia --project=. -e 'using Pkg; Pkg.add([
              Pkg.PackageSpec(url = "https://github.com/rafaqz/Rasters.jl", rev = "main") ,
              Pkg.PackageSpec(url = "https://github.com/asinghvi17/TernaryDiagrams.jl", rev = "as/improvements"),
              Pkg.PackageSpec(url = "https://github.com/xKDR/Survey.jl", rev = "main"),
              Pkg.PackageSpec(url = "https://github.com/MakieOrg/Makie.jl", rev = "master"),
              Pkg.PackageSpec(url = "https://github.com/MakieOrg/Makie.jl", subdir = "MakieCore", rev = "master"),
              Pkg.PackageSpec(url = "https://github.com/MakieOrg/Makie.jl", subdir = "CairoMakie", rev = "master"),
              Pkg.PackageSpec(url = "https://github.com/MakieOrg/GeoMakie.jl", rev = "master"),
          ])'
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v2
        with:
          files: lcov.info
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - uses: julia-actions/cache@v1
        with:
          cache-artifacts: true
      - run: |
          julia --project=docs -e 'using Pkg; Pkg.add([
              Pkg.PackageSpec(url = "https://github.com/rafaqz/Rasters.jl", rev = "main") ,
              Pkg.PackageSpec(url = "https://github.com/asinghvi17/TernaryDiagrams.jl", rev = "as/improvements"),
              Pkg.PackageSpec(url = "https://github.com/xKDR/Survey.jl", rev = "main"),
              Pkg.PackageSpec(url = "https://github.com/MakieOrg/Makie.jl", rev = "master"),
              Pkg.PackageSpec(url = "https://github.com/MakieOrg/Makie.jl", subdir = "MakieCore", rev = "master"),
              Pkg.PackageSpec(url = "https://github.com/MakieOrg/Makie.jl", subdir = "CairoMakie", rev = "master"),
              Pkg.PackageSpec(url = "https://github.com/MakieOrg/GeoMakie.jl", rev = "master"),
              Pkg.PackageSpec(url = "https://github.com/JuliaGeo/Proj.jl", rev = "as/geodesics"),
              Pkg.PackageSpec(url = "https://github.com/yeesian/ArchGDAL.jl", rev = "master"),
              Pkg.PackageSpec(path = "../Karmana.jl", name = "Karmana")
          ])'      
      - uses: julia-actions/julia-docdeploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          julia --project=docs -e '
            using Documenter: DocMeta, doctest
            using Karmana
            DocMeta.setdocmeta!(Karmana, :DocTestSetup, :(using Karmana); recursive=true)
            doctest(Karmana)'
